version: '3.8'

services:
  bot:
    build: ./
    command: /bot
    depends_on:
      - db
      - cache
    env_file:
      - .env
    ports:
      - 8000:8000
 
  db:
    restart: always
    image: postgres:latest
    env_file:
      - .env
    ports:
      - 5436:5432
    volumes:
      - ./data/postgres/pgdata:/var/lib/postgresql/data/pgdata

  cache:
    image: redis:6.2-alpine
    restart: always
    ports:
      - 6379:6379
    command: redis-server --save 20 1 --loglevel warning --requirepass 1
    volumes: 
      - cache:/data

volumes:
  cache:
    driver: local
